import assert from 'node:assert/strict';
import test from 'node:test';

import { runPrivateGameCheck } from '../../src/commands/run-private-game-check.ts';

test('private actual-card decks complete deterministic combat, Earth, Air, Fire, and Water scenarios', async () => {
  const result = await runPrivateGameCheck();
  assert.equal(result.classification, 'private-local_actual-cards_unranked-partial-rules');
  assert.equal(result.airMovement.movementMinion, 'Snallygaster');
  assert.equal(result.airMovement.twoStepDefend, true);
  assert.equal(result.airMovement.twoStepMoveAndAttack, true);
  assert.equal(result.airMovement.deck.atlas.reduce((total, card) => total + card.copies, 0), 30);
  assert.equal(result.airMovement.deck.spellbook.reduce((total, card) => total + card.copies, 0), 60);
  assert.equal(result.airMovement.replayVerified, true);
  assert.equal(result.airSummoning.roamingMinion, 'Roaming Monster');
  assert.equal(result.airSummoning.ordinaryRestricted, true);
  assert.equal(result.airSummoning.summonedAtEnemySite, true);
  assert.equal(result.airSummoning.deck.atlas.reduce((total, card) => total + card.copies, 0), 30);
  assert.equal(result.airSummoning.deck.spellbook.reduce((total, card) => total + card.copies, 0), 60);
  assert.deepEqual(result.airSummoning.deck, result.airMovement.deck);
  assert.equal(result.airSummoning.replayVerified, true);
  assert.equal(result.avatarSpellDrawn, true);
  assert.equal(result.charge.activatedOnSummon, true);
  assert.equal(result.genesis.siteDrawn, true);
  assert.equal(result.lethal.tougherMinionKilled, true);
  assert.equal(result.provider.affinityAdded, true);
  assert.equal(result.decks.north.atlas.reduce((total, card) => total + card.copies, 0), 30);
  assert.equal(result.decks.south.atlas.reduce((total, card) => total + card.copies, 0), 30);
  assert.equal(result.decks.north.spellbook.reduce((total, card) => total + card.copies, 0), 60);
  assert.equal(result.decks.south.spellbook.reduce((total, card) => total + card.copies, 0), 60);
  assert.equal(result.earthRamp.affinityAdded, true);
  assert.equal(result.earthRamp.manaUnavailableWhileSick, true);
  assert.equal(result.earthRamp.manaGained, 2);
  assert.equal(result.earthRamp.rampPaidFive, true);
  assert.equal(result.earthRamp.payoffCanMoveAndAttack, true);
  assert.equal(result.earthRamp.movingDefendUnavailable, true);
  assert.equal(result.earthRamp.genesisSiteDrawn, true);
  assert.equal(result.earthRamp.ghostTown, 'Ghost Town');
  assert.equal(result.earthRamp.ghostTownBonusMana, 1);
  assert.equal(result.earthRamp.ghostTownUnusedManaExpired, true);
  assert.equal(result.earthRamp.deathriteSiteDrawnBeforeCemetery, true);
  assert.equal(result.earthRamp.deck.atlas.reduce((total, card) => total + card.copies, 0), 30);
  assert.equal(result.earthRamp.deck.spellbook.reduce((total, card) => total + card.copies, 0), 60);
  assert.equal(result.earthRamp.replayVerified, true);
  assert.equal(result.fireResponse.lumberingGiant, 'Lumbering Giant');
  assert.equal(result.fireResponse.defendUnavailable, true);
  assert.equal(result.fireResponse.interceptUnavailable, true);
  assert.equal(result.fireResponse.deck.atlas.reduce((total, card) => total + card.copies, 0), 30);
  assert.equal(result.fireResponse.deck.spellbook.reduce((total, card) => total + card.copies, 0), 60);
  assert.equal(result.fireResponse.replayVerified, true);
  assert.equal(result.combat.northMinionDied, true);
  assert.equal(result.combat.southMinionDied, true);
  assert.equal(result.waterHealing.healingMinion, 'Muddy Pigs');
  assert.equal(result.waterHealing.healed, 3);
  assert.equal(result.waterHealing.healedBeforeCemetery, true);
  assert.equal(result.waterHealing.healingMinionDied, true);
  assert.equal(result.waterHealing.opponentMinionDied, true);
  assert.equal(result.waterHealing.deck.atlas.reduce((total, card) => total + card.copies, 0), 30);
  assert.equal(result.waterHealing.deck.spellbook.reduce((total, card) => total + card.copies, 0), 60);
  assert.equal(result.waterHealing.replayVerified, true);
  assert.equal(result.replayVerified, true);
});
